---

- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    update_cache: yes
    cache_valid_time: 3600 #1 hora
    name: "{{ item }}"
    state: latest
  with_items:
    - mysql-server-5.7
    - python-mysqldb
  become: yes

- name: 'Cria Banco de dados Mysql' 
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Cria usuário no bando de dados'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: '{{ item }}'
  with_items:
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes               
  notify:
    - restart mysql